CREATE TABLE [dbo].[pivot_nutrients] (

	[category] varchar(8000) NULL, 
	[last_edit_datetime] datetime2(6) NULL, 
	[LastDayOfMonth] date NULL, 
	[actual_q10_kgs] float NULL, 
	[planned_q10_kgs] float NULL, 
	[actual_qh_kgs] float NULL, 
	[planned_qh_kgs] float NULL, 
	[oee_net_percent] float NULL, 
	[oee_gross_percent] float NULL, 
	[scheduled_downtime_hrs] float NULL, 
	[scheduled_downtime_percent] float NULL, 
	[equipment_downtime_hrs] float NULL, 
	[equipment_downtime_percent] float NULL, 
	[process_downtime_hrs] float NULL, 
	[process_downtime_percent] float NULL, 
	[trouble_downtime_hrs] float NULL, 
	[trouble_downtime_percent] float NULL, 
	[packaging_yield_percent] float NULL, 
	[yield_qh_percent] float NULL, 
	[yield_q10_percent] float NULL, 
	[var_cost_q10_qh_prod] float NULL, 
	[var_cost_q10_q10_prod] float NULL, 
	[var_cost_qh_prod] float NULL, 
	[maintenance_cost_percent] float NULL, 
	[fixed_cost_percent] float NULL, 
	[global_safety_environmental_comments] varchar(8000) NULL, 
	[global_equipment_process_downtime_comments] varchar(8000) NULL, 
	[global_process_yield_comments] varchar(8000) NULL, 
	[global_scheduled_downtime_comments] varchar(8000) NULL, 
	[global_project_x_comments] varchar(8000) NULL, 
	[ntr_quality_issues] varchar(8000) NULL, 
	[global_summary_significant_items_month] varchar(8000) NULL, 
	[global_fixed_costs_total_maintenance_comments] varchar(8000) NULL, 
	[global_variable_cost_comments] varchar(8000) NULL
);